apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/$PROJECT_ID/locations/europe-west1-b/clusters/app-cluster
