apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - name: server-container
          image: europe-west1-docker.pkg.dev/$PROJECT_ID/app-docker-repo/app-server-image
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
